// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class ChatRoomUsers
    {
        [Key]
        public int id { get; set; }
        public int userId { get; set; }
        public int roomId { get; set; }
        public long jionTime { get; set; }

        [ForeignKey("roomId")]
        [InverseProperty("ChatRoomUsers")]
        public virtual ChatRoom room { get; set; }
        [ForeignKey("userId")]
        [InverseProperty("ChatRoomUsers")]
        public virtual User user { get; set; }
    }
}