// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class ChatRoom
    {
        public ChatRoom()
        {
            ChatContent = new HashSet<ChatContent>();
            ChatRoomUsers = new HashSet<ChatRoomUsers>();
        }

        [Key]
        public int id { get; set; }
        public long createTime { get; set; }
        public bool isGroup { get; set; }
        [StringLength(1000)]
        public string lastWords { get; set; }
        public long? lastWordsTime { get; set; }

        [InverseProperty("room")]
        public virtual ICollection<ChatContent> ChatContent { get; set; }
        [InverseProperty("room")]
        public virtual ICollection<ChatRoomUsers> ChatRoomUsers { get; set; }
    }
}