// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class ChatContentState
    {
        [Key]
        public int id { get; set; }
        public int userId { get; set; }
        public bool isRead { get; set; }
        public int chatContentId { get; set; }

        [ForeignKey("chatContentId")]
        [InverseProperty("ChatContentState")]
        public virtual ChatContent chatContent { get; set; }
        [ForeignKey("userId")]
        [InverseProperty("ChatContentState")]
        public virtual User user { get; set; }
    }
}