// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class EventsMap
    {
        [Key]
        public int edgeId { get; set; }
        public int source { get; set; }
        public int target { get; set; }
        public int gameId { get; set; }
    }
}