// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class EventTreeViewData
    {
        [Key]
        public int eventid { get; set; }
        [Required]
        [StringLength(500)]
        public string position { get; set; }

        [ForeignKey("eventid")]
        [InverseProperty("EventTreeViewData")]
        public virtual Event _event { get; set; }
    }
}