// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class GameBinding
    {
        [Key]
        public int id { get; set; }
        public int gameId { get; set; }
        [Required]
        [StringLength(500)]
        public string name { get; set; }
        public int type { get; set; }
        public int folderId { get; set; }
        [StringLength(1000)]
        public string cover { get; set; }
    }
}