// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class Lines
    {
        public Lines()
        {
            LinesChara = new HashSet<LinesChara>();
            LinesContent = new HashSet<LinesContent>();
            LinesVoice = new HashSet<LinesVoice>();
        }

        [Key]
        public int id { get; set; }
        public int eventId { get; set; }
        [StringLength(1000)]
        public string background { get; set; }
        [StringLength(1000)]
        public string backgroundStyle { get; set; }
        [StringLength(1000)]
        public string bgm { get; set; }
        public int next { get; set; }
        public int pre { get; set; }
        public int groupId { get; set; }

        [InverseProperty("lines")]
        public virtual ICollection<LinesChara> LinesChara { get; set; }
        [InverseProperty("lines")]
        public virtual ICollection<LinesContent> LinesContent { get; set; }
        [InverseProperty("lines")]
        public virtual ICollection<LinesVoice> LinesVoice { get; set; }
    }
}