// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class LinesBgm
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(1000)]
        public string bgm { get; set; }
        public int? bindingId { get; set; }
        public int? materialId { get; set; }

        [ForeignKey("id")]
        [InverseProperty("LinesBgm")]
        public virtual Lines idNavigation { get; set; }
    }
}