// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class MaterialFile
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(500)]
        public string name { get; set; }
        public int userId { get; set; }
        [Required]
        [StringLength(50)]
        public string type { get; set; }
        public int pid { get; set; }
        public long creactTime { get; set; }
        public long editTime { get; set; }
        public int groupId { get; set; }
        public int state { get; set; }
    }
}