// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class Material
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string type { get; set; }
        public int fileId { get; set; }
        [Required]
        [StringLength(1000)]
        public string link { get; set; }
        public int useId { get; set; }
        public long createTime { get; set; }
        public long editTime { get; set; }
    }
}