// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class Notification
    {
        [Key]
        public int id { get; set; }
        public int userId { get; set; }
        public int? linkId { get; set; }
        public int type { get; set; }
        [Required]
        [Column("notification")]
        [StringLength(1000)]
        public string notification1 { get; set; }
        public long time { get; set; }
        public int sourceUserId { get; set; }
        public bool isRead { get; set; }

        [ForeignKey("sourceUserId")]
        [InverseProperty("Notification")]
        public virtual User sourceUser { get; set; }
    }
}