// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class Star
    {
        [Key]
        public int id { get; set; }
        public int userId { get; set; }
        public int gameId { get; set; }
        public long starTime { get; set; }

        [ForeignKey("gameId")]
        [InverseProperty("Star")]
        public virtual Game game { get; set; }
    }
}