// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class Tag
    {
        [Key]
        public int tagId { get; set; }
        [Required]
        [Column("tag")]
        [StringLength(500)]
        public string tag1 { get; set; }
        public int gameId { get; set; }

        [ForeignKey("gameId")]
        [InverseProperty("Tag")]
        public virtual Game game { get; set; }
    }
}