// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class UserSave
    {
        [Key]
        public int id { get; set; }
        public long saveTime { get; set; }
        [Required]
        [StringLength(1000)]
        public string img { get; set; }
        [Required]
        [StringLength(1000)]
        public string eventName { get; set; }
        [Required]
        [StringLength(1000)]
        public string linesContent { get; set; }
        public int linesId { get; set; }
        [Required]
        [StringLength(2000)]
        public string choOptions { get; set; }
        public int saveIndex { get; set; }
        public int gameId { get; set; }
        public int userId { get; set; }
    }
}