// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class UserPlayedGame
    {
        [Key]
        public int id { get; set; }
        public int userId { get; set; }
        public int gameId { get; set; }
        public int playStart { get; set; }
        public int playLast { get; set; }
        public int playDuring { get; set; }
        public double progress { get; set; }
        [StringLength(1500)]
        public string ownEnd { get; set; }
        [StringLength(1500)]
        public string ownCG { get; set; }
    }
}