// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GalConnection.Entity
{
    public partial class UserGroup
    {
        [Key]
        public int id { get; set; }
        public int groupId { get; set; }
        public int userId { get; set; }
        public int role { get; set; }
        public long joinTime { get; set; }
    }
}